### PR TITLE
Merging rework into devel

### PR DESCRIPTION
**Pull request by rcannood**

### CODE REVIEW

**Comment by zouter** [comment]
You're lucky that github was not written by the authors of RCPP, which would have introduced a limit on the number of commits inside one pull request :wink:

**Comment by rcannood** [comment]
Now all devel needs is a lot of documentation :p (assuming it will be merged)

**Comment by zouter** [comment]
Oh :hankey: 

:running_man: :running_man: :running_man:

**Comment by zouter** [comment]
Are you happy with how it is now? I can help a bit with documentation...

Is it already in a good enough state for #7 ?

**Comment by rcannood** [comment]
I'm happy with the dyngen code (so yes wrt #7), I just haven't had time to
write proper (or any) roxygen documentation. I'll do this when I'm back
from holidays next week.

**Pull request merged**
